version: "3.8"
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - video_uploads:/app/uploads
    depends_on:
      - db
      - redis_hughie
    env_file: .env
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video_db
    
  worker:
    build: worker
    volumes:
      - ./worker/:/worker
      - video_uploads:/worker/uploads
    depends_on:
      - redis_hughie
      - app
    
  redis_dramatiq:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data


volumes:
  postgres_data:
  video_uploads:
  cache:
    driver: local