"""[updated] video model added length and size

Revision ID: 1cfd7046fa36
Revises: f9f88ff6f179
Create Date: 2022-07-24 06:28:29.190095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfd7046fa36'
down_revision = 'f9f88ff6f179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('size', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('length', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'length')
    op.drop_column('videos', 'size')
    # ### end Alembic commands ###
