"""added status as choice filed and remarks

Revision ID: 208f41ecf934
Revises: 2a9fa4513d6d
Create Date: 2022-07-24 05:35:07.501609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208f41ecf934'
down_revision = '2a9fa4513d6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('remarks', sa.String(length=100), nullable=True))
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('videos', 'remarks')
    # ### end Alembic commands ###
