"""added video status filed

Revision ID: ba5e60aaab49
Revises: 096a42c0c160
Create Date: 2022-07-21 09:01:26.331301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5e60aaab49'
down_revision = '096a42c0c160'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('status', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'status')
    # ### end Alembic commands ###
