"""updated to enum type on choice field

Revision ID: be7b2a6568b5
Revises: 1cfd7046fa36
Create Date: 2022-07-24 10:44:00.556196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7b2a6568b5'
down_revision = '1cfd7046fa36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
