"""added canceled choise

Revision ID: f9f88ff6f179
Revises: 208f41ecf934
Create Date: 2022-07-24 05:52:58.261743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f88ff6f179'
down_revision = '208f41ecf934'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
